### ISSUE TITLE
RecoveryFailure - Error Deserializing - Unknown Discriminator

### ISSUE THREAD

**Issue by amarwadi** [akkadotnet/Akka.Persistence.MongoDB#13]
Hello, after downgrading Akka to 1.0.4, I was successfully able to persist events into the Akka Event Journal store in Mongo. This is with reference to an earlier issue I created here: https://github.com/akkadotnet/Akka.Persistence.MongoDB/issues/12

When I close the system and re-run the application, the actor tries to recover from the messages that were persisted in MongoDb. In doing so, it runs into a Recovery Failure because it cannot find the Message Type.

An error occurred while deserializing the Payload property of class Akka.Persistence.MongoDb.Journal.JournalEntry: Unknown discriminator value 'CheckSeatMessage'.

Please note that CheckSeatMessage is a class as identified in the Gist. However, this class is in a separate project. Could this be an issue? I doubt it because I placed it in the same project and still received the issue.

https://gist.github.com/amarwadi/a887b26e14b0d42191b7

Here is the JSON in MongoDB:

{
  "_id" : "SectionActor_1",
  "PersistenceId" : "SectionActor",
  "SequenceNr" : NumberLong(1),
  "IsDeleted" : false,
  "Payload" : {
    "_t" : "CheckSeatMessage",
    "SeatKeys" : ["A", "B"],
    "RowKey" : "1",
    "SectionKey" : "1"
  }
}

**Comment by Silv3rcircl3** [comment]
@amarwadi

From the Readme ;-)

Serialization

The events and snapshots are stored as BsonDocument, so you need to register you types with the BsonClassMap before you can use your persistence actor.
Otherwise the recovery will fail and you receive a RecoveryFailure with the message:

An error occurred while deserializing the Payload property of class <Journal or Snapshot class>: Unknown discriminator value '<your type>'

**Comment by Silv3rcircl3** [comment]
@horusiath I think this one can be closed ;)
