### ISSUE TITLE
Lots of Failed to persist event type [  ... ] with sequence number [...]  for persistenceId [...]

### ISSUE THREAD

**Issue by DEllement** [akkadotnet/Akka.Persistence.MongoDB#150]
Hey guys,

i was wondering if anyone had any tips or direction toward the resolution of this kind of issue i have been trying to solve since a while.

So basically it seam that when the system is under load and lots of actor receive lots of events to persist i would often receive this kind of error, i have tried to increase the timeout from 10s to  20s without any luck.

Thank you

```
[ERROR][09/07/2020 22:47:20][Thread 0005][akka://.....] Failed to persist event type [......] with sequence number [11] for persistenceId [....].
Cause: Akka.Pattern.OpenCircuitException: Circuit Breaker is open; calls are failing fast
 ---> System.TimeoutException: Execution did not complete within the time allotted 20000 ms
   --- End of inner exception stack trace ---
   at Akka.Pattern.Open.Invoke[T](Func`1 body)
   at Akka.Persistence.Journal.AsyncWriteJournal.HandleWriteMessages(WriteMessages message)
```

**Comment by simonlaroche** [comment]
We solved that kind of error when recovering a lot of actors by using the Persistence Extras package https://github.com/petabridge/Akka.Persistence.Extras with its backoff supervisor.

If you are using Shard Regions with remember-entities set to true  it might be a good idea to change the recovery strategy to `constant`.  Otherwise the shard region will try to recover the entities as fast as possible

`akka.cluster.sharding.entity-recovery-strategy = "constant"`

**Comment by IgorFedchenko** [comment]
@DEllement Indeed, if underlying storage is overloaded, back-off strategy should help to reduce number of attempts that your actors/journals are making when failing to persist events. See more here: https://getakka.net/articles/persistence/event-sourcing.html#failures

You may also consider explicit event batching with `PersistAll` or `PersistAllAsync` to reduce the load to the journal.

I am closing this assuming that you have already resolved the issue with configuration/storage overloading, but feel free to reopen if you still have questions.

**Comment by DEllement** [comment]
Thank you for your recommendations @IgorFedchenko and @simonlaroche
